language: node_js
node_js:
  - stable
install:
  - npm install
  - npm install -g gitbook-cli
cache:
  directories:
    - node_modules
before_deploy:
  - npm run prepublish
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _book
    target_branch: gh-pages
    on:
      branch: master